name: Contact Form

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  submit_form:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read Email Template
        id: read_template
        uses: actions/download-artifact@v3
        with:
          name: email-template
          path: email_template.html

      - name: Send Email
        uses: actions/sendgrid-action@v1
        with:
          sendgrid_api_key: ${{ secrets.SENDGRID_API_KEY }}
          to: ConcussionFirearms@outlook.com
          from: noreply@concussionfirearms.github.io # Or custom domain
          subject: New Contact Form Submission
          html: |
            ${{ steps.read_template.outputs.email_template }}
            <p>Name: ${{ github.event.inputs.name }}</p>
            <p>Email: ${{ github.event.inputs.email }}</p>
            <p>Message: ${{ github.event.inputs.message }}</p>
