name: Contact Form

on:
  repository_dispatch:

jobs:
  submit_form:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Email Template
        uses: actions/download-artifact@v3
        id: download_email_template
        with:
          name: email-template
          path: email_template.html

      - name: Read Email Template Content  # New step to read the file
        id: read_email_template
        uses: actions/read-file@v1
        with:
          path: email_template.html

      - name: Send Email
        uses: actions/sendgrid-action@v1
        with:
          sendgrid_api_key: ${{ secrets.SENDGRID_API_KEY }}
          to: ConcussionFirearms@outlook.com
          from: noreply@concussionfirearms.github.io
          subject: New Contact Form Submission
          html: |
            ${{ steps.read_email_template.outputs.content }} <p>Name: ${{ github.event.inputs.name }}</p>
            <p>Email: ${{ github.event.inputs.email }}</p>
            <p>Message: ${{ github.event.inputs.message }}</p>
