name: Contact Form

on:
  workflow_dispatch: # For manual triggering (optional)
  repository_dispatch: # Triggered by form submission

jobs:
  submit_form:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Email Template
        uses: actions/download-artifact@v3
        with:
          name: email-template # Must match the artifact name in upload-email-template.yml
          path: email_template.html # Path where the artifact will be downloaded

      - name: Send Email
        uses: actions/sendgrid-action@v1
        with:
          sendgrid_api_key: ${{ secrets.SENDGRID_API_KEY }}
          to: ConcussionFirearms@outlook.com
          from: noreply@concussionfirearms.github.io # Or your custom domain
          subject: New Contact Form Submission
          html: |
            ${{ steps.download_email_template.outputs.email_template }}  <p>Name: ${{ github.event.inputs.name }}</p>
            <p>Email: ${{ github.event.inputs.email }}</p>
            <p>Message: ${{ github.event.inputs.message }}</p>
