name: Submit URLs to IndexNow

on:
  push:
    branches:
      - main
      - master

jobs:
  submit_urls:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Submit URLs to IndexNow
        env:
          API_KEY: ${{ secrets.INDEXNOW_API_KEY }}
        run: |
          BASE_URL="https://concussionfirearms.github.io"

          # Handle no previous commit case
          if [ $(git rev-list --count HEAD) -eq 1 ]; then
            echo "Only one commit found. Submitting all URLs."
            UPDATED_FILES=$(find . -type f -name '*.html' | sed 's|^./||')
          else
            UPDATED_FILES=$(git diff --name-only HEAD^ HEAD | grep '\.html') || true
          fi

          if [ -z "$UPDATED_FILES" ]; then
            echo "No HTML files updated. Skipping submission."
            exit 0
          fi

          echo "Using API key starting with: ${API_KEY:0:4}..."

          # Submit each updated file
          for file in $UPDATED_FILES; do
            URL="$BASE_URL/$file"
            echo "Submitting URL: $URL"
            
            # Make the request to IndexNow and capture response
            RESPONSE=$(curl -s -w "%{http_code}" -X POST "https://www.bing.com/indexnow?key=$API_KEY&url=$URL" -o response.txt)

            # Capture the response code
            HTTP_CODE=$(tail -n 1 <<< "$RESPONSE")

            # Check if the submission was successful (200 OK)
            if [ "$HTTP_CODE" -eq 200 ]; then
              echo "URL submitted successfully: $URL"
            else
              echo "Error submitting URL: $URL"
              echo "HTTP Code: $HTTP_CODE"
              echo "Response: $(cat response.txt)"
            fi
          done
