name: Submit URLs to IndexNow

on:
  push:
    branches:
      - main
      - master

jobs:
  submit_urls:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch the entire commit history

      - name: Submit URLs to IndexNow
        env:
          API_KEY: ${{ secrets.INDEXNOW_API_KEY }}
        run: |
          BASE_URL="https://concussionfirearms.github.io"
          
          # Handle no previous commit case
          if [ $(git rev-list --count HEAD) -eq 1 ]; then
            echo "Only one commit found. Submitting all URLs."
            UPDATED_FILES=$(find . -type f -name '*.html' | sed 's|^./||')
          else
            UPDATED_FILES=$(git diff --name-only HEAD^ HEAD | grep '\.html')
          fi

          if [ -z "$UPDATED_FILES" ]; then
            echo "No HTML files updated. Skipping submission."
            exit 0
          fi

          for file in $UPDATED_FILES; do
            URL="$BASE_URL/$file"
            echo "Submitting URL: $URL"
            curl -X POST "https://www.bing.com/indexnow?key=$API_KEY&url=$URL"
          done
